package centralRepo.interfaces;


/**
* centralRepo/interfaces/_RepositoryStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CentralRepoInterfaces.idl
* Sunday, March 3, 2019 5:08:25 AM IST
*/

public class _RepositoryStub extends org.omg.CORBA.portable.ObjectImpl implements centralRepo.interfaces.Repository
{

  public boolean registerLibraryServer (String library, String hostname, int port, String stubName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerLibraryServer", true);
                $out.write_string (library);
                $out.write_string (hostname);
                $out.write_long (port);
                $out.write_string (stubName);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registerLibraryServer (library, hostname, port, stubName        );
            } finally {
                _releaseReply ($in);
            }
  } // registerLibraryServer

  public centralRepo.interfaces.ServerDetail getServerDetails (String libId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getServerDetails", true);
                $out.write_string (libId);
                $in = _invoke ($out);
                centralRepo.interfaces.ServerDetail $result = centralRepo.interfaces.ServerDetailHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getServerDetails (libId        );
            } finally {
                _releaseReply ($in);
            }
  } // getServerDetails

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:centralRepo/interfaces/Repository:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RepositoryStub
