package centralRepo.interfaces;


/**
* centralRepo/interfaces/Repository.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CentralRepoInterfaces.idl
* Sunday, March 3, 2019 5:08:25 AM IST
*/

public interface Repository extends RepositoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final String HOSTNAME = "localhost";
  public static final int PORT = (int)(2000);
  public static final String STUBNAME = "Repository";
} // interface Repository
