package centralRepo.interfaces;


/**
* centralRepo/interfaces/RepositoryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CentralRepoInterfaces.idl
* Sunday, March 3, 2019 5:08:25 AM IST
*/

public abstract class RepositoryPOA extends org.omg.PortableServer.Servant
 implements centralRepo.interfaces.RepositoryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerLibraryServer", new java.lang.Integer (0));
    _methods.put ("getServerDetails", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // centralRepo/interfaces/Repository/registerLibraryServer
       {
         String library = in.read_string ();
         String hostname = in.read_string ();
         int port = in.read_long ();
         String stubName = in.read_string ();
         boolean $result = false;
         $result = this.registerLibraryServer (library, hostname, port, stubName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // centralRepo/interfaces/Repository/getServerDetails
       {
         String libId = in.read_string ();
         centralRepo.interfaces.ServerDetail $result = null;
         $result = this.getServerDetails (libId);
         out = $rh.createReply();
         centralRepo.interfaces.ServerDetailHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:centralRepo/interfaces/Repository:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Repository _this() 
  {
    return RepositoryHelper.narrow(
    super._this_object());
  }

  public Repository _this(org.omg.CORBA.ORB orb) 
  {
    return RepositoryHelper.narrow(
    super._this_object(orb));
  }


} // class RepositoryPOA
