package centralRepo.interfaces;


/**
* centralRepo/interfaces/RepositoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CentralRepoInterfaces.idl
* Sunday, March 3, 2019 5:08:25 AM IST
*/

abstract public class RepositoryHelper
{
  private static String  _id = "IDL:centralRepo/interfaces/Repository:1.0";

  public static void insert (org.omg.CORBA.Any a, centralRepo.interfaces.Repository that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static centralRepo.interfaces.Repository extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (centralRepo.interfaces.RepositoryHelper.id (), "Repository");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static centralRepo.interfaces.Repository read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RepositoryStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, centralRepo.interfaces.Repository value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static centralRepo.interfaces.Repository narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof centralRepo.interfaces.Repository)
      return (centralRepo.interfaces.Repository)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      centralRepo.interfaces._RepositoryStub stub = new centralRepo.interfaces._RepositoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static centralRepo.interfaces.Repository unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof centralRepo.interfaces.Repository)
      return (centralRepo.interfaces.Repository)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      centralRepo.interfaces._RepositoryStub stub = new centralRepo.interfaces._RepositoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
