package centralRepo.interfaces;


/**
* centralRepo/interfaces/ServerDetail.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CentralRepoInterfaces.idl
* Sunday, March 3, 2019 5:08:25 AM IST
*/

public interface ServerDetail extends ServerDetailOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerDetail
