package centralRepo.interfaces;


/**
* centralRepo/interfaces/ServerDetailOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CentralRepoInterfaces.idl
* Sunday, March 3, 2019 5:08:25 AM IST
*/

public interface ServerDetailOperations 
{
  String getHostname ();
  String getStubName ();
  int getPortNumber ();
} // interface ServerDetailOperations
