package centralRepo.interfaces;

/**
* centralRepo/interfaces/ServerDetailHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CentralRepoInterfaces.idl
* Sunday, March 3, 2019 5:08:25 AM IST
*/

public final class ServerDetailHolder implements org.omg.CORBA.portable.Streamable
{
  public centralRepo.interfaces.ServerDetail value = null;

  public ServerDetailHolder ()
  {
  }

  public ServerDetailHolder (centralRepo.interfaces.ServerDetail initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = centralRepo.interfaces.ServerDetailHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    centralRepo.interfaces.ServerDetailHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return centralRepo.interfaces.ServerDetailHelper.type ();
  }

}
