package centralRepo.interfaces;


/**
* centralRepo/interfaces/ServerDetailPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CentralRepoInterfaces.idl
* Sunday, March 3, 2019 5:08:25 AM IST
*/

public abstract class ServerDetailPOA extends org.omg.PortableServer.Servant
 implements centralRepo.interfaces.ServerDetailOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getHostname", new java.lang.Integer (0));
    _methods.put ("getStubName", new java.lang.Integer (1));
    _methods.put ("getPortNumber", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // centralRepo/interfaces/ServerDetail/getHostname
       {
         String $result = null;
         $result = this.getHostname ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // centralRepo/interfaces/ServerDetail/getStubName
       {
         String $result = null;
         $result = this.getStubName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // centralRepo/interfaces/ServerDetail/getPortNumber
       {
         int $result = (int)0;
         $result = this.getPortNumber ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:centralRepo/interfaces/ServerDetail:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerDetail _this() 
  {
    return ServerDetailHelper.narrow(
    super._this_object());
  }

  public ServerDetail _this(org.omg.CORBA.ORB orb) 
  {
    return ServerDetailHelper.narrow(
    super._this_object(orb));
  }


} // class ServerDetailPOA
