package server.interfaces;


/**
* server/interfaces/BooksHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterfaces.idl
* Friday, March 8, 2019 1:13:06 PM IST
*/

abstract public class BooksHelper
{
  private static String  _id = "IDL:server/interfaces/Books:1.0";

  public static void insert (org.omg.CORBA.Any a, server.interfaces.Book[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.interfaces.Book[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = server.interfaces.BookHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (server.interfaces.BooksHelper.id (), "Books", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.interfaces.Book[] read (org.omg.CORBA.portable.InputStream istream)
  {
    server.interfaces.Book value[] = null;
    int _len0 = istream.read_long ();
    value = new server.interfaces.Book[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = server.interfaces.BookHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.interfaces.Book[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      server.interfaces.BookHelper.write (ostream, value[_i0]);
  }

}
