package server.interfaces;


/**
* server/interfaces/BookPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterfaces.idl
* Friday, March 8, 2019 1:13:06 PM IST
*/

public abstract class BookPOA extends org.omg.PortableServer.Servant
 implements server.interfaces.BookOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getName", new java.lang.Integer (0));
    _methods.put ("getId", new java.lang.Integer (1));
    _methods.put ("getNumberOfCopies", new java.lang.Integer (2));
    _methods.put ("setName", new java.lang.Integer (3));
    _methods.put ("setId", new java.lang.Integer (4));
    _methods.put ("setNumberOfCopies", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // server/interfaces/Book/getName
       {
         String $result = null;
         $result = this.getName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // server/interfaces/Book/getId
       {
         String $result = null;
         $result = this.getId ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // server/interfaces/Book/getNumberOfCopies
       {
         int $result = (int)0;
         $result = this.getNumberOfCopies ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // server/interfaces/Book/setName
       {
         String name = in.read_string ();
         this.setName (name);
         out = $rh.createReply();
         break;
       }

       case 4:  // server/interfaces/Book/setId
       {
         String id = in.read_string ();
         this.setId (id);
         out = $rh.createReply();
         break;
       }

       case 5:  // server/interfaces/Book/setNumberOfCopies
       {
         int numberOfCopies = in.read_long ();
         this.setNumberOfCopies (numberOfCopies);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:server/interfaces/Book:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Book _this() 
  {
    return BookHelper.narrow(
    super._this_object());
  }

  public Book _this(org.omg.CORBA.ORB orb) 
  {
    return BookHelper.narrow(
    super._this_object(orb));
  }


} // class BookPOA
