package server.interfaces;


/**
* server/interfaces/BookOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterfaces.idl
* Friday, March 8, 2019 1:13:06 PM IST
*/

public interface BookOperations 
{
  String getName ();
  String getId ();
  int getNumberOfCopies ();
  void setName (String name);
  void setId (String id);
  void setNumberOfCopies (int numberOfCopies);
} // interface BookOperations
