package server.interfaces;


/**
* server/interfaces/BookHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterfaces.idl
* Friday, March 8, 2019 1:13:06 PM IST
*/

abstract public class BookHelper
{
  private static String  _id = "IDL:server/interfaces/Book:1.0";

  public static void insert (org.omg.CORBA.Any a, server.interfaces.Book that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.interfaces.Book extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (server.interfaces.BookHelper.id (), "Book");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.interfaces.Book read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BookStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.interfaces.Book value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static server.interfaces.Book narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.interfaces.Book)
      return (server.interfaces.Book)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server.interfaces._BookStub stub = new server.interfaces._BookStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static server.interfaces.Book unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.interfaces.Book)
      return (server.interfaces.Book)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server.interfaces._BookStub stub = new server.interfaces._BookStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
