package server.interfaces;


/**
* server/interfaces/LibraryOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterfaces.idl
* Friday, March 8, 2019 1:13:06 PM IST
*/

public interface LibraryOperationsOperations 
{
  boolean userExists (String userId);

  //Manager operations
  boolean addItem (String managerID, String itemID, String itemName, int quantity) throws server.interfaces.GeneralException;
  int removeItem (String managerID, String itemID, int quantity) throws server.interfaces.GeneralException;
  server.interfaces.Book[] listAvailableItems (String managerID) throws server.interfaces.GeneralException;

  //Student operations
  int borrowItem (String userID, String itemID, String numberOfDays) throws server.interfaces.GeneralException;
  server.interfaces.Book[] findItem (String userID, String itemName) throws server.interfaces.GeneralException;
  boolean returnItem (String userID, String itemID) throws server.interfaces.GeneralException;
  boolean addToWaitingList (String userID, String itemID) throws server.interfaces.GeneralException;
  boolean addToWaitingListOverloaded (String userID, String itemID, String oldItemID) throws server.interfaces.GeneralException;
  int exchangeItem (String userID, String newItemID, String oldItemID) throws server.interfaces.GeneralException;
} // interface LibraryOperationsOperations
