package server.interfaces;

/**
* server/interfaces/LibraryOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterfaces.idl
* Friday, March 8, 2019 1:13:06 PM IST
*/

public final class LibraryOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public server.interfaces.LibraryOperations value = null;

  public LibraryOperationsHolder ()
  {
  }

  public LibraryOperationsHolder (server.interfaces.LibraryOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.interfaces.LibraryOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.interfaces.LibraryOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.interfaces.LibraryOperationsHelper.type ();
  }

}
