package server.interfaces;

/**
* server/interfaces/OperationsEnumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterfaces.idl
* Friday, March 8, 2019 1:13:06 PM IST
*/

public final class OperationsEnumHolder implements org.omg.CORBA.portable.Streamable
{
  public server.interfaces.OperationsEnum value = null;

  public OperationsEnumHolder ()
  {
  }

  public OperationsEnumHolder (server.interfaces.OperationsEnum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.interfaces.OperationsEnumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.interfaces.OperationsEnumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.interfaces.OperationsEnumHelper.type ();
  }

}
