package server.interfaces;


/**
* server/interfaces/OperationsEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterfaces.idl
* Friday, March 8, 2019 1:13:06 PM IST
*/

public class OperationsEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 6;
  private static server.interfaces.OperationsEnum[] __array = new server.interfaces.OperationsEnum [__size];

  public static final int _BORROW_ITEM = 0;
  public static final server.interfaces.OperationsEnum BORROW_ITEM = new server.interfaces.OperationsEnum(_BORROW_ITEM);
  public static final int _FIND_ITEM = 1;
  public static final server.interfaces.OperationsEnum FIND_ITEM = new server.interfaces.OperationsEnum(_FIND_ITEM);
  public static final int _RETURN_ITEM = 2;
  public static final server.interfaces.OperationsEnum RETURN_ITEM = new server.interfaces.OperationsEnum(_RETURN_ITEM);
  public static final int _ADD_TO_WAITING_LIST = 3;
  public static final server.interfaces.OperationsEnum ADD_TO_WAITING_LIST = new server.interfaces.OperationsEnum(_ADD_TO_WAITING_LIST);
  public static final int _BOOK_BORROWED = 4;
  public static final server.interfaces.OperationsEnum BOOK_BORROWED = new server.interfaces.OperationsEnum(_BOOK_BORROWED);
  public static final int _BOOK_AVAILABLE = 5;
  public static final server.interfaces.OperationsEnum BOOK_AVAILABLE = new server.interfaces.OperationsEnum(_BOOK_AVAILABLE);

  public int value ()
  {
    return __value;
  }

  public static server.interfaces.OperationsEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected OperationsEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class OperationsEnum
